#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
  path: /random/number
  controller: App\Controller\RandomNumberController::number

blog_list:
  path: /blog/{page}
  # the controller value has the format 'controller_class::method_name'
  controller: App\Controller\BlogController::list
  defaults:
    page: 1
  requirements:
    page: '\d+'

  # if the action is implemented as the __invoke() method of the
  # controller class, you can skip the '::method_name' part:
  # controller: App\Controller\BlogController

blog_show:
  path: /blog/{slug}
  controller: App\Controller\BlogController::show

tell_me_about_you:
  path: /about_you
  controller: App\Controller\TellMeAboutYouController::setView

user_index:
  path: /user
  methods:
    - GET
  defaults:
    _controller: App\Controller\UserController::index

user_new:
  path: /user/new
  methods:
    - GET
    - POST
  defaults:
    _controller: App\Controller\UserController::new

user_show:
  path: /user/{id}
  methods:
    - GET
  defaults:
    _controller: App\Controller\UserController::show

user_edit:
  path: /user/{id}/edit
  methods:
    - GET
    - POST
  defaults:
    _controller: App\Controller\UserController::edit

user_delete:
  path: /user/{id}
  methods:
    - DELETE
  defaults:
    _controller: App\Controller\UserController::delete