#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
  path: /random/number
  controller: App\Controller\RandomNumberController::number

blog_list:
  path: /blog/{page}
  # the controller value has the format 'controller_class::method_name'
  controller: App\Controller\BlogController::list
  defaults:
    page: 1
  requirements:
    page: '\d+'

  # if the action is implemented as the __invoke() method of the
  # controller class, you can skip the '::method_name' part:
  # controller: App\Controller\BlogController

blog_show:
  path: /blog/{slug}
  controller: App\Controller\BlogController::show

tell_me_about_you:
  path: /about_you
  controller: App\Controller\TellMeAboutYouController::setView

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout