App\Entity\User:
  type: entity
  table: user
  repositoryClass: App\Repository\UserRepository
  id:
    id:
      column: id
      type: integer
      nullable: false
      generator:
        strategy: AUTO
  fields:
    name:
      column: name
      type: text
      length: 50
      nullable: false
    email:
      column: email
      type: string
      length: 32
      unique: true
      options:
        fixed: true
        comment: Email do usuario
      nullable: false
    password:
      column: password
      type: string
      nullable: false
    sex:
      column: sex
      type: text
      nullable: true
    birthDate:
      column: birth_date
      type: datetime
      nullable: false
    roles:
      column: roles
      type: array
      nullable: false
  lifecycleCallbacks: {  }